groups:
- name: targets
  rules:
  - alert: MI_service_down
    expr: service_status == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "{{$labels.name}} service is unhealthy"
      description: "Service is down on {{ $labels.env }}. Please check the health"

  - alert: DiskSpace<95%
    expr: (node_filesystem_avail_bytes{mountpoint="/"}*100) / node_filesystem_size_bytes < 95 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 1s
    labels:
      severity: warning
    #  cluster: test
    annotations:
    # summary: "Host out of disk space (instance {{ $labels.instance }})"
      description: "Disk usage is = {{humanize $value }}"


