global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'S&P Monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

#  - job_name: 'cadvisor'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

#  - job_name: 'exporter'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['exporter:5002']

# CONFIGURACIONES SERVERS MULTINUCLEO
  - job_name: 'Rasberry4'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.50:9100']

  - job_name: 'Rasberry3'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.82:9100']

  - job_name: 'infosec'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.107:9100']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']

#READ FROM INFLUXDB 
remote_read:
  - url: "http://10.196.41.25:8086/api/v1/prom/read?db=telegraf&u=telegraf&p=Mult1nucl30."


